MQTT = {
    'CONNETION_STATUS': {
        'SUCCESSFUL': 0,
        'INCCORRECT_PROTOCOL_VERSION': 1,
        'INVALID_CLIENT_IDENTIFIER': 2,
        'SERVER_UNAVAILABLE': 3,
        'BAD_USERNAME_OR_PASSWORD': 4,
        'UNAUTHORIZED': 5
    },
    'TIMEOUT': 3  # 3s
}
